FROM balenalib/raspberry-pi-debian:latest
MAINTAINER Name rich@cs.ucsb.edu

RUN apt-get update 
RUN apt-get -y install ninja-build g++-9 cmake g++ git

WORKDIR /root

RUN mkdir -p src
WORKDIR /root/src
RUN git clone https://github.com/Mayhem-lab/cspot
WORKDIR /root/src/cspot
run git submodule update --init --recursive
RUN mkdir build
WORKDIR /root/src/cspot/build
RUN mkdir bin
RUN cmake -G Ninja ..
RUN ninja
RUN ninja install
